### ISSUE TITLE
Requires a middleware function error

### ISSUE THREAD

**Issue by nami-cagla** [A11yWatch/node-iframe#6]
Hi, thank you for this project! 👍 
However, I am getting an error when trying to start my server.

Here's the code:

`const express = require('express')
const createIframe = require('node-iframe')
const app = express()

app.use(createIframe)

app.get('/iframe', (req, res) => {
    res.createIframe({
        url: req.query.url,
    })
})`

and I get this error

> throw new TypeError('app.use() requires a middleware function')
    ^
TypeError: app.use() requires a middleware function

I am using node vv14.4.0

Any idea on how to solve this? :(
Thank you!!

**Comment by j-mendez** [comment]
Your welcome, I tried to see if I could reproduce the issue and everything
seems fine. I made an example project here that you can pull down and use
https://github.com/A11yWatch/node-iframe-example. What OS are you using?
Check to see if the example app works on your machine.

>

**Comment by j-mendez** [comment]
@nami-cagla figured out the issue, change the import for require js or you
can use `import` to avoid needing to use default const createIframe =
require("node-iframe").default;

Need to update the lib to be a common module to avoid needing to do this.

Thank you for the help, I updated the readme instructions to reflect this.

**Comment by nami-cagla** [comment]
Hi, thank you so much for the reply!
I have tried and tested that it is working with 
`const createIframe = require("node-iframe").default`

I just have one more question, sorry.
I am using google.com to test, but there's an error in getting the images. I thought it was a google thing, but I also tried to use it with a site that I created and still the image is still not being displayed. It seems like the css and js files are also not being read.
Is there any solution for this one?

![image](https://user-images.githubusercontent.com/59039396/110721587-31d77680-8254-11eb-8782-cf64b385f2c9.png)

**Comment by j-mendez** [comment]
@nami-cagla cors issue with the resource on localhost. If you deploy your
page to a server cors issues might go away depending on the website. Try to
add

app.get("/iframe", (req, res) => {
  res.createIframe({
    url: req.query.url,
    baseHref: req.query.baseHref, // optional: determine how to
control link redirects,
    config: { cors: { img: true } } // optional: determine element
cors or inlining #shape src/iframe.ts#L34
  });});

or


const {
  configureResourceControl} = require("node-iframe");


configureResourceControl({
  cors: { img: true }});

Currently the package only handles inlining scripts, we would need to add
img inlining to overcome cors issues locally. Going to add this to a tasks
on the board.

**Comment by nami-cagla** [comment]
I changed bits of your code with:

baseHref: req.query.url,
config: { cors: { img: false } } 

and now images, css, and js files are being read.

Thank you so much for your help!!

**Comment by j-mendez** [comment]
Awesome, glad you were able to resolve this!
